apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition-app
  labels:
    app: image-recognition-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-recognition-app
  template:
    metadata:
      labels:
        app: image-recognition-app
    spec:
      containers:
        - name: image-recognition-app
          image: docker.io/gabrielgodoy/image-recognition-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
