apiVersion: v1
kind: Service
metadata:
  name: recognition-service
spec:
  selector:
    app: image-recognition-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition-app
spec:
  selector:
    matchLabels:
      app: image-recognition-app
  replicas: 2
  template:
    metadata:
      labels:
        app: image-recognition-app
    spec:
      containers:
        - name: image-recognition-app
          image: docker.io/gabrielgodoy/image-recognition-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080