apiVersion: v1
kind: Service
metadata:
  name: recognition-service
spec:
  type: LoadBalancer
  selector:
    app: image-recognition-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
