apiVersion: v1
kind: Service
metadata:
  name: recognition-service
spec:
  selector:
    app: image-recognition-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
